const $=id=>document.getElementById(id);let token="";
async function api(path,options={}){const r=await fetch(path,{...options,headers:{Accept:"application/json","Content-Type":"application/json","X-SkyTrace-Admin":token,...(options.headers||{})}});let p={};try{p=await r.json()}catch{}if(!r.ok||p.ok===false)throw new Error(p.error||`Request failed (${r.status})`);return p}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[m])}
function table(el,rows,columns,actions){if(!rows.length){el.innerHTML="<tr><td class='muted'>No data yet.</td></tr>";return}el.innerHTML=`<thead><tr>${columns.map(c=>`<th>${esc(c[1])}</th>`).join("")}${actions?"<th>ACTION</th>":""}</tr></thead><tbody>${rows.map(row=>`<tr>${columns.map(c=>`<td>${esc(typeof c[2]==="function"?c[2](row):row[c[0]])}</td>`).join("")}${actions?`<td>${actions(row)}</td>`:""}</tr>`).join("")}</tbody>`}
async function load(){const [s,u,p,c]=await Promise.all([api("/v1/admin/summary"),api("/v1/admin/users?limit=150"),api("/v1/admin/purchases?limit=150"),api("/v1/admin/codes?limit=250")]);const labels={users:"Users",activeSessions:"Sessions",paidPurchases:"Purchases",stripeRevenueMinor:"Stripe GBP",activeCodes:"Active codes",cloudItems:"Cloud items",historyPoints:"History pts"};$("stats").innerHTML=Object.entries(s.summary).map(([k,v])=>`<div class="card stat"><span class="muted">${labels[k]||k}</span><strong>${k==="stripeRevenueMinor"?`£${(Number(v)/100).toFixed(2)}`:Number(v).toLocaleString()}</strong></div>`).join("");table($("usersTable"),u.rows,[["username","USERNAME"],["purchases","PURCHASES"],["entitlements","ENTITLEMENTS"],["created_at","CREATED",r=>new Date(r.created_at).toLocaleString()]]);table($("purchasesTable"),p.rows,[["username","USER"],["product_key","PRODUCT"],["source","SOURCE"],["status","STATUS"],["created_at","CREATED",r=>new Date(r.created_at).toLocaleString()]]);table($("codesTable"),c.rows,[["id","ID"],["product_key","PRODUCT"],["label","LABEL"],["uses","USES",r=>`${r.uses}/${r.max_uses}`],["last4","HINT",r=>`${r.prefix}-…-${r.last4}`],["expires_at","EXPIRES",r=>r.expires_at?new Date(r.expires_at).toLocaleString():"never"],["revoked_at","STATUS",r=>r.revoked_at?"revoked":r.expires_at&&r.expires_at<Date.now()?"expired":"active"]],r=>r.revoked_at?"":`<button class="danger" data-revoke="${esc(r.id)}">Revoke</button>`);document.querySelectorAll("[data-revoke]").forEach(b=>b.onclick=()=>revoke(b.dataset.revoke))}
async function login(){token=$("token").value.trim();try{await api("/v1/admin/summary");sessionStorage.setItem("skytrace.adminToken",token);$("login").classList.add("hidden");$("app").classList.remove("hidden");await load()}catch(e){$("loginMsg").textContent=e.message;token=""}}
async function generate(){try{$("codeStatus").textContent="Generating…";const p=await api("/v1/admin/codes/generate",{method:"POST",body:JSON.stringify({productKey:$("codeProduct").value,count:Number($("codeCount").value),maxUses:Number($("codeUses").value),days:Number($("codeDays").value),label:$("codeLabel").value})});$("codeOutput").textContent=p.codes.join("\n");$("codeStatus").textContent=`Created ${p.codes.length}`;await load()}catch(e){$("codeStatus").textContent=e.message}}
async function revoke(id){if(!confirm("Revoke this code?"))return;await api("/v1/admin/codes/revoke",{method:"POST",body:JSON.stringify({id})});await load()}
async function grant(){try{const p=await api("/v1/admin/grant",{method:"POST",body:JSON.stringify({username:$("grantUser").value,productKey:$("grantProduct").value})});$("grantStatus").textContent=`Granted to ${p.username}.`;await load()}catch(e){$("grantStatus").textContent=e.message}}
$("loginBtn").onclick=login;$("token").onkeydown=e=>{if(e.key==="Enter")login()};$("generateBtn").onclick=generate;$("grantBtn").onclick=grant;$("refreshBtn").onclick=load;$("lockBtn").onclick=()=>{sessionStorage.removeItem("skytrace.adminToken");location.reload()};token=sessionStorage.getItem("skytrace.adminToken")||"";if(token){$("token").value=token;login()}
